class Param:

    NOTIFICATION_NONE = -1
    NOTIFICATION_BELL = 0
    NOTIFICATION_FACE = 1

    NOTIFICATION_STRING_NONE = 'dummy'
    NOTIFICATION_STRING_BELL = 'bell'
    NOTIFICATION_STRING_FACE = 'face'